---
- name: Install Nginx
  hosts: vps
  tasks:
    - name: Cache update
      apt:
        update_cache: yes

    - name: Installing Nginx
      apt:
        name: nginx
        state: present

    - name: start service 
      service: 
         name: nginx
         state: started
         enabled: yes

    - name: Allow 
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: copy file
      copy:
        src: nginx.conf
        dest: /etc/nginx/


    - name: copy files
      ansible.builtin.template:
        src: virtualhost1_template.conf.j2
        dest: /etc/nginx/conf.d/virtualhost1.conf
        owner: root
        group: root
        mode : 0644

    - name: copy virtualhost2
      ansible.builtin.template:
        src: virtualhost2_template.conf.j2
        dest: /etc/nginx/conf.d/virtualhost2.conf
        owner: root
        group: root
        mode : 0644


    - name: Create symlink VirtualHost1
      file:
       src: /etc/nginx/conf.d/virtualhost1.conf
       dest: /etc/nginx/sites-enabled/virtualhost1.conf
       state: link

    
   - name: Create symlink VirtualHost2
     file:
       src: /etc/nginx/conf.d/virtualhost2.conf
       dest: /etc/nginx/sites-enabled/virtualhost2.conf
       state: link



    - name: nginx reload
      service:
        name: nginx
        state: reloaded
