- name: Install nginx
  hosts: localhost
  tasks:
    - name: Cache update
      ansible.legacy.apt:
        update_cache: true
    - name: Installing nginx
      ansible.legacy.apt:
        name: nginx
        state: present
    - name: Start service
      ansible.legacy.service:
        name: nginx
        state: started
        enabled: true
    - name: Allow
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp
