---
- name: Install Nginx
  hosts: vps
  tasks:
    - name: Cache update
      apt:
        update_cache: yes

    - name: Installing Nginx
      apt:
        name: nginx
        state: latest

    - name: start service 
      service: 
         name: nginx
         state: started
         enabled: yes

    - name: Allow 
      ufw:
        rule: allow
        port: '80'
        proto: tcp